import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
// eslint-disable-next-line @typescript-eslint/no-var-requires
const sharp = require('sharp');
import { ImageValidationResult } from './image-validation.interface';

@Injectable()
export class ImageValidationService {
  private readonly logger = new Logger(ImageValidationService.name);
  private readonly apiKey: string;
  private readonly model: string;
  private readonly apiUrl: string;

  constructor(private readonly configService: ConfigService) {
    this.apiKey =
      this.configService.get<string>('ai.gemini.apiKey') ||
      this.configService.get<string>('ai.gemma.apiKey') ||
      '';
    this.model =
      this.configService.get<string>('ai.gemini.model') || 'gemini-1.5-flash';
    this.apiUrl =
      this.configService.get<string>('ai.gemini.apiUrl') ||
      'https://generativelanguage.googleapis.com/v1beta/models';
  }

  /**
   * Validates an uploaded image using the Gemini API.
   * Identifies whether the image is a screenshot or AI-generated.
   * If flagged, returns isValid: false with a descriptive rejectionReason.
   */
  async validateImage(
    buffer: Buffer,
    mimeType: string,
    originalName?: string,
  ): Promise<ImageValidationResult> {
    // 1. If not an image (e.g. PDF/DOC attachment), bypass image verification
    if (!mimeType || !mimeType.startsWith('image/')) {
      return {
        isValid: true,
        isScreenshot: false,
        isAiGenerated: false,
        confidence: 1.0,
        rejectionReason: null,
        providerUsed: 'none (non-image file)',
      };
    }

    // 2. If Gemini API key is not configured, fall back to heuristic verification
    if (!this.apiKey) {
      this.logger.warn(
        'GEMINI_API_KEY is not configured. Utilizing metadata heuristic validation.',
      );
      return this.heuristicImageCheck(buffer, mimeType, originalName);
    }

    // 3. Prepare and optimize image buffer for Gemini multimodal input
    let preparedBuffer = buffer;
    let effectiveMime = mimeType;

    try {
      // Downscale to max 1024px to minimize transfer size and latency for vision model
      preparedBuffer = await sharp(buffer)
        .resize({ width: 1024, height: 1024, fit: 'inside', withoutEnlargement: true })
        .jpeg({ quality: 85 })
        .toBuffer();
      effectiveMime = 'image/jpeg';
    } catch (optErr) {
      this.logger.debug(
        `Sharp image optimization skipped: ${optErr.message}. Using original buffer.`,
      );
      preparedBuffer = buffer;
      effectiveMime = mimeType;
    }

    const base64Data = preparedBuffer.toString('base64');
    const endpoint = `${this.apiUrl}/${this.model}:generateContent?key=${this.apiKey}`;

    const prompt = `You are an expert image forensic AI analyzing photos uploaded to a civic/societal problem reporting portal.
Your task is to examine the provided image and determine if:
1. It is a SCREENSHOT (e.g. mobile phone screens, computer desktop/windows, social media posts, chat applications, browser windows, or photographs taken of a digital screen).
2. It is AI-GENERATED (e.g. generated by Midjourney, DALL-E, Stable Diffusion, Flux, or similar tools; characterized by diffusion artifacts, plastic/hyper-smooth skin/textures, distorted hands/text/anatomy, unnatural lighting, or prompt-style hyperrealism).
3. It is an AUTHENTIC REAL-WORLD CAMERA PHOTOGRAPH (taken in the real physical world documenting infrastructure, roads, water, clinics, schools, waste, etc.).

EVALUATION RULES:
- Mark isScreenshot: true if the image contains mobile status bars (clock, battery, signal), app headers, navigation bars, browser chrome, desktop window frames, chat bubbles, or screen pixel grid moiré.
- Mark isAiGenerated: true if the image contains synthetic artifacts, plastic textures, generative distortions, or surreal compositions typical of AI image generation.
- Mark isValid: true ONLY if the image is an authentic, real-world photograph taken with a camera.
- If isScreenshot is true OR isAiGenerated is true, mark isValid: false.
- When isValid is false, provide a polite, clear rejectionReason explaining why the upload is rejected.

Respond ONLY with a valid JSON object matching this schema:
{
  "isValid": boolean,
  "isScreenshot": boolean,
  "isAiGenerated": boolean,
  "confidence": number,
  "rejectionReason": string | null,
  "details": string
}`;

    const requestBody = {
      contents: [
        {
          role: 'user',
          parts: [
            {
              inlineData: {
                mimeType: effectiveMime,
                data: base64Data,
              },
            },
            {
              text: prompt,
            },
          ],
        },
      ],
      generationConfig: {
        temperature: 0.1,
        topK: 32,
        topP: 0.95,
        maxOutputTokens: 1024,
        responseMimeType: 'application/json',
      },
    };

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 10000); // 10s timeout

    try {
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(requestBody),
        signal: controller.signal,
      });

      clearTimeout(timeoutId);

      if (!response.ok) {
        const errorText = await response.text();
        this.logger.error(`Gemini API Error HTTP ${response.status}: ${errorText}`);
        throw new Error(`Gemini API responded with status ${response.status}`);
      }

      const data = await response.json();
      let responseText = data.candidates?.[0]?.content?.parts?.[0]?.text || '{}';

      const jsonMatch = responseText.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        responseText = jsonMatch[0];
      }

      const parsed = JSON.parse(responseText);
      return this.sanitizeValidationResult(parsed, this.model);
    } catch (err: any) {
      clearTimeout(timeoutId);
      this.logger.warn(
        `Gemini image validation failed: ${err.message}. Running heuristic fallback.`,
      );
      return this.heuristicImageCheck(buffer, mimeType, originalName);
    }
  }

  /**
   * Sanitizes and normalizes the raw response from Gemini.
   */
  private sanitizeValidationResult(
    raw: any,
    provider: string,
  ): ImageValidationResult {
    const isScreenshot = Boolean(raw.isScreenshot);
    const isAiGenerated = Boolean(raw.isAiGenerated);
    const isValid = !isScreenshot && !isAiGenerated && Boolean(raw.isValid !== false);
    const confidence = Math.min(
      1.0,
      Math.max(0.0, typeof raw.confidence === 'number' ? raw.confidence : 0.9),
    );

    let rejectionReason: string | null = null;
    if (!isValid) {
      if (isScreenshot && isAiGenerated) {
        rejectionReason =
          raw.rejectionReason ||
          'Upload rejected: The image appears to be a screenshot of AI-generated content. Please upload an authentic camera photograph.';
      } else if (isScreenshot) {
        rejectionReason =
          raw.rejectionReason ||
          'Upload rejected: The image appears to be a screenshot. Please upload an authentic, direct photograph of the issue taken with a camera.';
      } else if (isAiGenerated) {
        rejectionReason =
          raw.rejectionReason ||
          'Upload rejected: The image appears to be AI-generated. Please upload an authentic, real-world photograph of the issue.';
      } else {
        rejectionReason =
          raw.rejectionReason ||
          'Upload rejected: The image is not an authentic real-world photograph.';
      }
    }

    return {
      isValid,
      isScreenshot,
      isAiGenerated,
      confidence,
      rejectionReason,
      details: raw.details || '',
      providerUsed: provider,
    };
  }

  /**
   * Heuristic fallback for offline/development or API unavailability.
   * Inspects metadata, filename keywords, and image dimensions for screenshot/AI patterns.
   */
  public async heuristicImageCheck(
    buffer: Buffer,
    mimeType: string,
    originalName?: string,
  ): Promise<ImageValidationResult> {
    const filename = (originalName || '').toLowerCase();

    // 1. Filename keyword checks
    const screenshotKeywords = ['screenshot', 'screen_shot', 'screen-shot', 'prntscr', 'snip', 'capture'];
    const aiKeywords = ['midjourney', 'dall-e', 'dalle', 'stable_diffusion', 'stablediffusion', 'ai_gen', 'generated'];

    for (const kw of screenshotKeywords) {
      if (filename.includes(kw)) {
        return {
          isValid: false,
          isScreenshot: true,
          isAiGenerated: false,
          confidence: 0.9,
          rejectionReason:
            'Upload rejected: The image appears to be a screenshot. Please upload an authentic, direct photograph of the issue taken with a camera.',
          details: `Detected screenshot keyword "${kw}" in file metadata.`,
          providerUsed: 'Metadata Heuristic Engine',
        };
      }
    }

    for (const kw of aiKeywords) {
      if (filename.includes(kw)) {
        return {
          isValid: false,
          isScreenshot: false,
          isAiGenerated: true,
          confidence: 0.9,
          rejectionReason:
            'Upload rejected: The image appears to be AI-generated. Please upload an authentic, real-world photograph of the issue.',
          details: `Detected AI generation keyword "${kw}" in file metadata.`,
          providerUsed: 'Metadata Heuristic Engine',
        };
      }
    }

    // 2. Inspect image metadata via Sharp if available
    try {
      const metadata = await sharp(buffer).metadata();

      // Check common phone screen aspect ratios without EXIF camera metadata
      const hasExif = Boolean(metadata.exif && metadata.exif.length > 0);
      const width = metadata.width || 0;
      const height = metadata.height || 0;

      // Check for exact mobile screen resolutions
      const commonScreenResolutions = [
        [1080, 2400], [1080, 2340], [1170, 2532], [1284, 2778], [1290, 2796],
        [1179, 2556], [1080, 1920], [750, 1334], [1440, 3120], [1440, 3200]
      ];

      const isCommonScreenRes = commonScreenResolutions.some(
        ([w, h]) => (width === w && height === h) || (width === h && height === w),
      );

      // PNG format with exact screen resolution and no camera EXIF data strongly indicates screenshot
      if (metadata.format === 'png' && isCommonScreenRes && !hasExif) {
        return {
          isValid: false,
          isScreenshot: true,
          isAiGenerated: false,
          confidence: 0.85,
          rejectionReason:
            'Upload rejected: The image appears to be a screenshot. Please upload an authentic, direct photograph of the issue taken with a camera.',
          details: `Image dimensions (${width}x${height}) and PNG format without camera EXIF indicate a device screenshot.`,
          providerUsed: 'Metadata Heuristic Engine',
        };
      }
    } catch (metaErr) {
      this.logger.debug(`Heuristic metadata check error: ${metaErr.message}`);
    }

    // Default to valid if no screenshot/AI signals were detected
    return {
      isValid: true,
      isScreenshot: false,
      isAiGenerated: false,
      confidence: 0.75,
      rejectionReason: null,
      details: 'No screenshot or AI generation indicators detected.',
      providerUsed: 'Metadata Heuristic Engine',
    };
  }
}
