import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
// eslint-disable-next-line @typescript-eslint/no-var-requires
const sharp = require('sharp');
import {
  ImageValidationResult,
  ImageAuthenticityStatus,
} from './image-validation.interface';
import { MediaTypeUtil } from '../../utils/media-type.util';
import { HeicConverterUtil } from '../../utils/heic-converter.util';

@Injectable()
export class ImageValidationService {
  private readonly logger = new Logger(ImageValidationService.name);
  private readonly apiKey: string;
  private readonly model: string;
  private readonly apiUrl: string;
  private readonly confidenceThreshold: number;

  constructor(private readonly configService: ConfigService) {
    this.apiKey =
      this.configService.get<string>('ai.gemini.apiKey') ||
      this.configService.get<string>('ai.gemma.apiKey') ||
      '';
    this.model =
      this.configService.get<string>('ai.gemini.model') || 'gemini-1.5-flash';
    this.apiUrl =
      this.configService.get<string>('ai.gemini.apiUrl') ||
      'https://generativelanguage.googleapis.com/v1beta/models';
    const confThresh = this.configService.get<number>('ai.confidenceThreshold');
    this.confidenceThreshold =
      typeof confThresh === 'number' && !isNaN(confThresh) ? confThresh : 0.75;
  }

  /**
   * Validates an uploaded image using the Gemini API.
   * Identifies whether the image is a screenshot or AI-generated.
   * If flagged, returns isValid: false with a descriptive rejectionReason.
   */
  async validateImage(
    buffer: Buffer,
    mimeType: string,
    originalName?: string,
  ): Promise<ImageValidationResult> {
    const resolvedMime = MediaTypeUtil.resolveEffectiveMimeType(
      buffer,
      mimeType,
      originalName,
    );

    // 1. If not an image (e.g. PDF/DOC/video attachment), bypass image verification
    if (!resolvedMime || !resolvedMime.startsWith('image/')) {
      return {
        isValid: true,
        isScreenshot: false,
        isAiGenerated: false,
        confidence: 1.0,
        status: 'genuine',
        threshold: this.confidenceThreshold,
        rejectionReason: null,
        providerUsed: 'none (non-image file)',
      };
    }

    // 2. Normalize HEIC/HEIF to JPEG before downscaling/AI processing
    let processingBuffer = buffer;
    let effectiveMime = resolvedMime;

    if (MediaTypeUtil.isHeic(buffer, originalName, resolvedMime)) {
      try {
        processingBuffer = await HeicConverterUtil.convertHeicToJpeg(buffer);
        effectiveMime = 'image/jpeg';
      } catch (convErr: any) {
        this.logger.warn(`HEIC pre-conversion notice: ${convErr.message}`);
      }
    }

    // 3. If Gemini API key is not configured, fall back to heuristic verification
    if (!this.apiKey) {
      this.logger.warn(
        'GEMINI_API_KEY is not configured. Utilizing metadata heuristic validation.',
      );
      return this.heuristicImageCheck(processingBuffer, effectiveMime, originalName);
    }

    // 4. Prepare and optimize image buffer for Gemini multimodal input
    let preparedBuffer = processingBuffer;

    try {
      // Downscale to max 1024px to minimize transfer size and latency for vision model
      preparedBuffer = await sharp(processingBuffer)
        .resize({ width: 1024, height: 1024, fit: 'inside', withoutEnlargement: true })
        .jpeg({ quality: 85 })
        .toBuffer();
      effectiveMime = 'image/jpeg';
    } catch (optErr) {
      this.logger.debug(
        `Sharp image optimization skipped: ${optErr.message}. Using normalized buffer.`,
      );
      preparedBuffer = processingBuffer;
    }

    const base64Data = preparedBuffer.toString('base64');
    const endpoint = `${this.apiUrl}/${this.model}:generateContent?key=${this.apiKey}`;

    const prompt = `You are an expert image forensic AI analyzing photos uploaded to a civic/societal problem reporting portal.
Your task is to examine the provided image and determine if:
1. It is a SCREENSHOT (e.g. mobile phone screens, computer desktop/windows, social media posts, chat applications, browser windows, or photographs taken of a digital screen).
2. It is AI-GENERATED (e.g. generated by Midjourney, DALL-E, Stable Diffusion, Flux, or similar tools; characterized by generative diffusion artifacts, impossible anatomy/hands, nonsensical/garbled text, unphysical geometry, or prompt-style hyperrealism).
3. It is an AUTHENTIC REAL-WORLD CAMERA PHOTOGRAPH (taken in the physical world documenting infrastructure, roads, water, clinics, schools, waste, etc.).

CRITICAL GUIDELINES FOR AUTHENTIC MOBILE PHOTOS:
- Modern smartphone cameras (iPhone, Android, Samsung, Pixel) apply computational HDR, multi-frame noise reduction, edge sharpening, and digital zoom. These enhancements can create smooth surfaces or high local contrast.
- Photos converted from HEIC/HEIF, or compressed as JPEG/WebP, will contain normal compression block artifacts.
- DO NOT flag an image as AI-generated solely due to compression, mobile camera noise reduction, smooth lighting, or lens flare.
- Flag isAiGenerated: true ONLY if there are clear generative model anomalies (e.g. surreal synthetic textures, hallucinated background structures, anatomical mutilations, impossible physics).

EVALUATION RULES:
- Mark isScreenshot: true if the image contains mobile status bars (clock, battery, signal), app headers, navigation bars, browser chrome, desktop window frames, chat bubbles, or screen pixel grid moiré.
- Mark isAiGenerated: true if the image contains generative synthetic artifacts or impossible generative structures.
- Return a confidence score between 0.0 and 1.0 reflecting your certainty.
- Mark isValid: true ONLY if the image is an authentic, real-world photograph taken with a camera.
- If isScreenshot is true OR isAiGenerated is true, mark isValid: false.
- When isValid is false, provide a polite, clear rejectionReason explaining why the upload is rejected.

Respond ONLY with a valid JSON object matching this schema:
{
  "isValid": boolean,
  "isScreenshot": boolean,
  "isAiGenerated": boolean,
  "confidence": number,
  "rejectionReason": string | null,
  "details": string
}`;

    const requestBody = {
      contents: [
        {
          role: 'user',
          parts: [
            {
              inlineData: {
                mimeType: effectiveMime,
                data: base64Data,
              },
            },
            {
              text: prompt,
            },
          ],
        },
      ],
      generationConfig: {
        temperature: 0.1,
        topK: 32,
        topP: 0.95,
        maxOutputTokens: 1024,
        responseMimeType: 'application/json',
      },
    };

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 10000); // 10s timeout

    try {
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(requestBody),
        signal: controller.signal,
      });

      clearTimeout(timeoutId);

      if (!response.ok) {
        const errorText = await response.text();
        this.logger.error(`Gemini API Error HTTP ${response.status}: ${errorText}`);
        throw new Error(`Gemini API responded with status ${response.status}`);
      }

      const data = await response.json();
      let responseText = data.candidates?.[0]?.content?.parts?.[0]?.text || '{}';

      const jsonMatch = responseText.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        responseText = jsonMatch[0];
      }

      const parsed = JSON.parse(responseText);
      return this.sanitizeValidationResult(parsed, this.model);
    } catch (err: any) {
      clearTimeout(timeoutId);
      this.logger.warn(
        `Gemini image validation failed: ${err.message}. Running heuristic fallback.`,
      );
      return this.heuristicImageCheck(processingBuffer, effectiveMime, originalName);
    }
  }

  /**
   * Sanitizes and normalizes the raw response from Gemini, applying the confidence threshold.
   */
  private sanitizeValidationResult(
    raw: any,
    provider: string,
  ): ImageValidationResult {
    const rawScreenshot = Boolean(raw.isScreenshot);
    const rawAiGenerated = Boolean(raw.isAiGenerated);
    const confidence = Math.min(
      1.0,
      Math.max(0.0, typeof raw.confidence === 'number' ? raw.confidence : 0.9),
    );

    // Apply configurable confidence threshold to prevent false-positive rejection of citizen photos
    let isAiGenerated = false;
    let isScreenshot = rawScreenshot;
    let status: ImageAuthenticityStatus = 'genuine';

    if (rawScreenshot) {
      status = 'screenshot';
    }

    if (rawAiGenerated) {
      if (confidence >= this.confidenceThreshold) {
        isAiGenerated = true;
        status = isScreenshot ? 'screenshot' : 'likely_ai';
      } else {
        // AI flagged with low/moderate confidence: treat as suspicious but avoid hard rejection
        status = 'suspicious';
        this.logger.warn(
          `Image flagged as potentially AI-generated but below threshold (${confidence.toFixed(2)} < ${this.confidenceThreshold}). Marked as suspicious.`,
        );
      }
    }

    const isValid = !isScreenshot && !isAiGenerated;

    let rejectionReason: string | null = null;
    if (!isValid) {
      if (isScreenshot && isAiGenerated) {
        rejectionReason =
          raw.rejectionReason ||
          'Upload rejected: The image appears to be a screenshot of AI-generated content. Please upload an authentic camera photograph.';
      } else if (isScreenshot) {
        rejectionReason =
          raw.rejectionReason ||
          'Upload rejected: The image appears to be a screenshot. Please upload an authentic, direct photograph of the issue taken with a camera.';
      } else if (isAiGenerated) {
        rejectionReason =
          raw.rejectionReason ||
          'Upload rejected: The image appears to be AI-generated. Please upload an authentic, real-world photograph of the issue.';
      } else {
        rejectionReason =
          raw.rejectionReason ||
          'Upload rejected: The image is not an authentic real-world photograph.';
      }
    }

    return {
      isValid,
      isScreenshot,
      isAiGenerated,
      confidence,
      status,
      threshold: this.confidenceThreshold,
      rejectionReason,
      details: raw.details || '',
      providerUsed: provider,
    };
  }


  /**
   * Heuristic fallback for offline/development or API unavailability.
   * Inspects metadata, filename keywords, and image dimensions for screenshot/AI patterns.
   */
  public async heuristicImageCheck(
    buffer: Buffer,
    mimeType: string,
    originalName?: string,
  ): Promise<ImageValidationResult> {
    const filename = (originalName || '').toLowerCase();

    // 1. Filename keyword checks
    const screenshotKeywords = ['screenshot', 'screen_shot', 'screen-shot', 'prntscr', 'snip', 'capture'];
    const aiKeywords = ['midjourney', 'dall-e', 'dalle', 'stable_diffusion', 'stablediffusion', 'ai_gen', 'generated'];

    for (const kw of screenshotKeywords) {
      if (filename.includes(kw)) {
        return {
          isValid: false,
          isScreenshot: true,
          isAiGenerated: false,
          confidence: 0.9,
          status: 'screenshot',
          threshold: this.confidenceThreshold,
          rejectionReason:
            'Upload rejected: The image appears to be a screenshot. Please upload an authentic, direct photograph of the issue taken with a camera.',
          details: `Detected screenshot keyword "${kw}" in file metadata.`,
          providerUsed: 'Metadata Heuristic Engine',
        };
      }
    }

    for (const kw of aiKeywords) {
      if (filename.includes(kw)) {
        return {
          isValid: false,
          isScreenshot: false,
          isAiGenerated: true,
          confidence: 0.9,
          status: 'likely_ai',
          threshold: this.confidenceThreshold,
          rejectionReason:
            'Upload rejected: The image appears to be AI-generated. Please upload an authentic, real-world photograph of the issue.',
          details: `Detected AI generation keyword "${kw}" in file metadata.`,
          providerUsed: 'Metadata Heuristic Engine',
        };
      }
    }

    // 2. Inspect image metadata via Sharp if available
    try {
      const metadata = await sharp(buffer).metadata();

      // Check common phone screen aspect ratios without EXIF camera metadata
      const hasExif = Boolean(metadata.exif && metadata.exif.length > 0);
      const width = metadata.width || 0;
      const height = metadata.height || 0;

      // Check for exact mobile screen resolutions
      const commonScreenResolutions = [
        [1080, 2400], [1080, 2340], [1170, 2532], [1284, 2778], [1290, 2796],
        [1179, 2556], [1080, 1920], [750, 1334], [1440, 3120], [1440, 3200]
      ];

      const isCommonScreenRes = commonScreenResolutions.some(
        ([w, h]) => (width === w && height === h) || (width === h && height === w),
      );

      // PNG format with exact screen resolution and no camera EXIF data strongly indicates screenshot
      if (metadata.format === 'png' && isCommonScreenRes && !hasExif) {
        return {
          isValid: false,
          isScreenshot: true,
          isAiGenerated: false,
          confidence: 0.85,
          status: 'screenshot',
          threshold: this.confidenceThreshold,
          rejectionReason:
            'Upload rejected: The image appears to be a screenshot. Please upload an authentic, direct photograph of the issue taken with a camera.',
          details: `Image dimensions (${width}x${height}) and PNG format without camera EXIF indicate a device screenshot.`,
          providerUsed: 'Metadata Heuristic Engine',
        };
      }
    } catch (metaErr) {
      this.logger.debug(`Heuristic metadata check error: ${metaErr.message}`);
    }

    // Default to valid if no screenshot/AI signals were detected
    return {
      isValid: true,
      isScreenshot: false,
      isAiGenerated: false,
      confidence: 0.75,
      status: 'genuine',
      threshold: this.confidenceThreshold,
      rejectionReason: null,
      details: 'No screenshot or AI generation indicators detected.',
      providerUsed: 'Metadata Heuristic Engine',
    };
  }
}
